### ISSUE TITLE
Revisión formularios 24/10/17

### ISSUE THREAD

**Issue by aralvarez** [DarkYnesT/DIW#1]
Se pedía utilizar como método de envío "get", si es posible. Sin embargo, en la mayoría se utiliza el método "post".

En el ejercicio 10, falta el variable name para el campo select.

Cuando estén corregidos, vuelve a subirlos...

**Comment by DarkYnesT** [comment]
están corregidos!

**Comment by aralvarez** [comment]
¿Has corregido el ejercicio 10?

**Comment by DarkYnesT** [comment]
esta corregido!
